apiVersion: v1
kind: Service
metadata:
  name: ecomm-order-service
  namespace: ecomm-dev
spec:
  selector:
    app: ecomm-order-service
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
  type: NodePort
